name: Update EPG

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias à meia-noite
  push:
    branches:
      - main

jobs:
  update-epg:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Garante permissões de escrita no repositório

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install googleapis axios fs zlib

    - name: Run EPG script
      run: node script.js
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}

    - name: List files in directory
      run: ls -la

    - name: Resolve conflicts, commit, and push changes
      run: |
        git config --local user.email "you@example.com"
        git config --local user.name "Your Name"
        git stash
        git pull origin main --rebase
        git stash pop
        git add -A
        git rebase --continue || git rebase --skip  # Se o rebase falhar, tenta pular
        git commit -m "Update EPG"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
