name: Update EPG

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias à meia-noite
  push:
    branches:
      - main

jobs:
  update-epg:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Garante permissões de escrita no repositório

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install googleapis axios fs zlib

    - name: Run EPG script
      run: node script.js
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}

    - name: List files in directory
      run: ls -la

    - name: Stash, pull, and commit changes
      run: |
        git config --local user.email "you@example.com"
        git config --local user.name "Your Name"
        git stash  # Faz um stash das mudanças locais
        git pull origin main  # Puxa as últimas alterações do repositório remoto
        git stash pop  # Aplica as mudanças do stash
        git add -f epg.xml epg.xml.gz  # Força a adição dos arquivos
        git commit -m "Update EPG"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
